name: Generate Snake Contribution

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours to update your snake animation.
  workflow_dispatch:        # Allows you to run it manually from the Actions tab.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out your repository
      - uses: actions/checkout@v3

      # Generate the snake animation using Platane/snk action
      - uses: Platane/snk@v3
        with:
          github_user_name: "Rayan-141"
          outputs: |
            dist/github-snake.svg

      # Publish the generated image to an 'output' branch (optional, but helps keep your main branch clean)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
